### ISSUE TITLE
Generic Compiler Pass to replace admin class or document class

### ISSUE THREAD

**Issue by ElectricMaxxx** [symfony-cmf/sonata-admin-integration-bundle#41]
I currently had an idea how to replace the editable admin/document class configuration in a nice way.
On my sandbox PR (https://github.com/symfony-cmf/cmf-sandbox/pull/332) i created a very specific compiler pass to replace the document class for the StaticContentAdmin, what about a configuration here like:

```yml
admin_classes:
    cmf_sonata_admin_integration.content.admin: My\Special\Admin\Class
    ....
document_classes:
   cmf_sonata_admin_integration.content.admin: AppBundle\Document\DemoSeoContent
   ....
``` 

We could then create a more generic compiler pass to replace the class or the 2. argument of a service (key) with the given value.
